# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b3b37b47014f840c3be13ea7d83938f759c8fed6cae970fffaf3400a20cfc296d08ada0bd09fd04a7ce96597db3dae3ab62a94a9e10617243964482ce0d5aac4

test:
  secret_key_base: 4d2878dc0333193a5362ebfa6bdcf6991df6c2ccc2c764a387320eb47ece36e5269f37136aa41c1be2a755758f09300568ecb343c383fcb333b7f26098a19cbc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
